version: '2'

services:
  wordpress:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - .:/var/www/html/wp-content/themes/cxo-magazine-wp
      - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - 8081:80
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: password
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: password
